### ISSUE TITLE
Horse Sinks Instead of Swims

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#14] opened 2021-04-24 19:39 UTC
## Expected Behavior
When swimming, the horse is expected to swim and be able to step out of water.

## Current Behavior
Horse will start to sink and won't be able to get up out of the water, also a water source block will disappear?

## Possible Solution
??

## Steps to Reproduce

1. Mount a tamed, tacked up SWEM horse.
2. Plop (specifically) into water. (If you just walk in, it works. If you plop, it doesnt.)
3.
4.

## Environment Info:
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yes

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment] 2021-04-24 23:26
Plop: running fast into deep water, or jumping into deep water.

It floats lower than eye level, and once you hit a block to try and get out of water, it "realises" it fucked up, and just cancel the upward movement and sink.

**Comment by MagnusHJensen** [comment] 2021-04-30 13:41
This is fixed with version: `1.16.5-0.21.2.1-Alpha` and up.

This was caused by having the inverse force to low, so when you added gravity into the eqaution, meaning you drop into water from heights, or fast speeds, the small multiplier was not enough to keep the horse up, hence the sinking.

Now it comes with small bobbing, but it floats no matter what, (makes it more realistic?) idk.

**Closed by MagnusHJensen** 2021-04-30 13:41 UTC
Labels: bug
