### ISSUE TITLE
Horses will not drink water even by a water source

### ISSUE THREAD

**Issue by BrookexKayla** [cavecomputing/SWE-Alpha-Test#57] opened 2021-05-14 22:44 UTC
almost everyone's horses on stars private server are stuck in a trot and cannot go above it because their horses are too thirsty.

**Comment by MagnusHJensen** [comment] 2021-05-15 14:28
This was caused by a hunger issue, this has been fixed with version: `1.16.5-0.22.4.0-Alpha` and up.

**Closed by MagnusHJensen** 2021-05-15 14:28 UTC
