### ISSUE TITLE
Horse and Block Collision?

### ISSUE THREAD

**Issue by AlaharranHonor** [cavecomputing/SWE-Alpha-Test#18] opened 2021-04-24 20:56 UTC
## Expected Behavior
To one-step over blocks consistently without issue.

## Current Behavior
When running through tight areas like forests, the horse becomes stuck on the ground blocks and vibrates violently until I reverse and go forward again. 

## Possible Solution
IDK

## Steps to Reproduce

1. Mount a tamed, tacked up SWEM horse.
2. Ride through forest at higher speeds.
3.
4.

## Environment Info:
SWEM Version: 0.21.0.1-Alpha
Does this happen in singleplayer? IDK
Does this happen in multiplayer? Yee

## If a crash has happened, provide the logs.

**Comment by MagnusHJensen** [comment] 2021-04-24 21:31
This is a cause of really high speeds with canter/gallop at Speed 5 (mby 4).

**Comment by MagnusHJensen** [comment] 2021-04-30 12:25
This from what I can see was caused by not resetting the speed correctly, in singleplayer it would crash the game, but in servers it would just complain and not crash, and then manipulating the movement speed of the entity, was not going to be right going forward, meaning it could most likely obtain abnormal speeds, that it glitched out.

This is fixed with version: `1.16.5-0.21.2.0-Alpha`

**Closed by MagnusHJensen** 2021-04-30 12:25 UTC
Labels: bug
